//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wantsan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class buyukluk_values
    {
        public int id { get; set; }
        public int buyukluk_id { get; set; }
        public int teklif_id { get; set; }
        public string value1 { get; set; }
        public string value2 { get; set; }
        public string value3 { get; set; }
    
        public virtual buyukluk_tipleri buyukluk_tipleri { get; set; }
    }
}
