//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wantsan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pozisyonlar
    {
        public int id { get; set; }
        public int Teklif_ID { get; set; }
        public string pozNo { get; set; }
        public string Cinsi { get; set; }
        public Nullable<int> Miktar { get; set; }
        public Nullable<int> BirimFiyatı { get; set; }
        public Nullable<int> Tutarı { get; set; }
    
        public virtual teklif teklif { get; set; }
    }
}
