//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wantsan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class teklif
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public teklif()
        {
            this.Pozisyonlar = new HashSet<Pozisyonlar>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string sayin { get; set; }
        public string isin_adi { get; set; }
        public string ilgi { get; set; }
        public Nullable<int> toplambedel { get; set; }
        public string teslimsuresi { get; set; }
        public string teslim_yeri { get; set; }
        public string odemesarti { get; set; }
        public string garanti { get; set; }
        public string obsiyon { get; set; }
        public Nullable<int> poz_tutar_toplam { get; set; }
        public Nullable<int> poz_kdv { get; set; }
        public Nullable<int> poz_toplam { get; set; }
        public Nullable<int> iskonto_orani { get; set; }
        public Nullable<int> iskonto_tutari { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pozisyonlar> Pozisyonlar { get; set; }
    }
}
